dataset: ???
algorithm:
  voting:
    voting_num: 120       # 3 degree
    # angle_tol: 1.5        # 10 degree
    angle_tol: 0.35       # 5 degree
    translation2pc: False
    rotation_cluster: True
    multi_candidate: True
    candidate_threshold: 0.5
    rotation_multi_neighbor: True
    neighbor_threshold: 5
    bmm_size: 100000

trained:
  path: {
    "Microwave": "./outputs/train/formal_microwave_2024_01_16_12_16_57", 
    "Refrigerator": "./outputs/train/formal_refrigerator_2024_01_17_22_52_26", 
    "Safe": "./outputs/train/formal_safe_2024_01_17_23_01_44", 
    "StorageFurniture": "./outputs/train/formal_storagefurniture_2024_01_18_11_13_43", 
    "Drawer": "./outputs/train/formal_drawer_2024_01_18_11_18_23", 
    "WashingMachine": "./outputs/train/formal_washingmachine_2024_01_17_23_07_14"
    }
